- name: restart ssh service
  hosts: '{{ vmname }}'
  hosts: localhost
  connection: local
  gather_facts: no
  become: true
  tasks:
  - service:
     name: sshd
     state: restarted
  - service:
     name: firewalld
     state: stop
